Add ability to set minimum required version for build
clutter/mdma pull request #189
Opened 2020-09-29 20:26 UTC by gfu-clutter

## Context
This gives the ability to specificy the minimum supported version of an app. Necessary groundwork to start enforcing app versions to be updated to at least a certain point.

<img width="1131" alt="Screen Shot 2020-09-29 at 1 25 13 PM" src="https://user-images.githubusercontent.com/40773985/94611976-4e0fca00-0257-11eb-8406-cd41582f17e6.png">

2020-09-30 20:43 UTC, erikstrottmann requested changes
One section of code you can delete, one quirk of Rails you taught me, and one place you should add an additional scope. Otherwise looks good!

2020-09-30 20:43 UTC, erikstrottmann commented on app/controllers/builds/minimum_supported_versions_controller.rb
> +    def build_params
Looks like `update` is accessing `params` directly instead of `build_params`. `build_params` doesn’t seem necessary.

2020-09-30 20:43 UTC, erikstrottmann commented on app/models/build.rb
> +               if: -> { minimum_supported_version && saved_change_to_minimum_supported_version? }
TIL that as of Rails 5.2, `foo_changed?` now only returns `true` if there are changes that haven’t been saved yet (which now has an alias, `will_save_change_to_foo?`). For changes that were just saved, like in an `after_update` block, you want to use `saved_change_to_foo?`. Good to know!

https://www.fastruby.io/blog/rails/upgrades/active-record-5-1-api-changes

2020-09-30 20:43 UTC, erikstrottmann commented on db/migrate/20200929185128_add_minimum_supported_version_to_device.rb
> +      dir.up { Build.order(id: :asc).first.update_column(:minimum_supported_version, true) }
This should include the `external` scope, because internal builds shouldn’t be the minimum-supported version.

2020-09-30 22:31 UTC, gfu-clutter commented on app/controllers/builds/minimum_supported_versions_controller.rb
> +    def build_params
done

2020-09-30 22:31 UTC, gfu-clutter commented on db/migrate/20200929185128_add_minimum_supported_version_to_device.rb
> +      dir.up { Build.order(id: :asc).first.update_column(:minimum_supported_version, true) }
done

2020-09-30 22:53 UTC, erikstrottmann approved these changes

2020-10-07 23:31 UTC, gfu-clutter commented
closing since released from https://github.com/clutter/mdma/pull/190

2020-10-07 23:31 UTC, closed without merging